// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _3aWI_Projekt.Database;

#nullable disable

namespace _3aWI_Projekt.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250603073006_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClassroomID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SchoolClass")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SchoolID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Track")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("ClassroomID");

                    b.HasIndex("SchoolID");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("_3aWI_Projekt.Models.Classroom", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SchoolID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("SchoolID");

                    b.ToTable("Classrooms");
                });

            modelBuilder.Entity("_3aWI_Projekt.Models.School", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Schools");
                });

            modelBuilder.Entity("Student", b =>
                {
                    b.HasOne("_3aWI_Projekt.Models.Classroom", null)
                        .WithMany("Students")
                        .HasForeignKey("ClassroomID");

                    b.HasOne("_3aWI_Projekt.Models.School", null)
                        .WithMany("Students")
                        .HasForeignKey("SchoolID");
                });

            modelBuilder.Entity("_3aWI_Projekt.Models.Classroom", b =>
                {
                    b.HasOne("_3aWI_Projekt.Models.School", null)
                        .WithMany("Classrooms")
                        .HasForeignKey("SchoolID");
                });

            modelBuilder.Entity("_3aWI_Projekt.Models.Classroom", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("_3aWI_Projekt.Models.School", b =>
                {
                    b.Navigation("Classrooms");

                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
